tcoupling:
  thermostat: HOOVER_EVANS
  coupling-freq: 1
  heating-steps: 3
  nh-chain-length: 10
mpi:
  # grid dimensions; the number of processors used in mpirun should equal the product
  dimensions: [ 2, 2, 2 ]
