run:
  integrator: VELOCITY_VERLET
  steps: 1000
  dt: 0.002
  tinit: 0     # time of the zeroth timestep
box:
  L: [ 60.1, 60.1, 60.1 ]
  cell-dims: [ 10, 10, 10 ]
neighbor-search:
  rcut: 5.2
  rshell: 3.14
  interval: 10
tcoupling:
  thermostat: HOOVER_EVANS
  coupling-freq: 1
  heating-steps: 3
  nh-chain-length: 10
output:
  interval: 20
mpi:
  # grid dimensions; the number of processors used in mpirun should equal the product
  dimensions: [ 2, 2, 2 ]
