---
plane_count: 500                  # number of planes to generate
plane_distribution: 'one_airport' # how to distribute planes initially. 'uniform', 'one_airport'
plane_use_hdf5_data: false        # when false, all planes must fall back to default type
log_statistics: true              # log simulation statistics at regular intervals
log_statistics_interval: 50       # interval for log_statistics. irrelevant when log_statistics: false
log_trace-viewer: false           # log output for trace-viewer at simulator completion
running_option: 'non-distributed' # required simulator option. 'non-distributed', 'yawns', 'null_message'
running_time: 1000                # length of simulation runtime
...
