find_package(OpenMP)
if (NOT OPENMP_FOUND)
#    if (${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
#        message("System plaform is '${CMAKE_SYSTEM_NAME}'; will attempt to build while assuming OpenMP is installed by MacPorts...")
#        set(OpenMP_C_FLAGS "-I/opt/local/include/libomp -L/opt/local/lib/libomp -fopenmp=libomp")
#        set(OpenMP_CXX_FLAGS "-I/opt/local/include/libomp -L/opt/local/lib/libomp -fopenmp=libomp")
#    else()
        message( FATAL_ERROR "${BoldRed}OpenMP does not appear to be available for ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}!${ColourReset}" )
#    endif()
endif()
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
add_definitions( -DLAP_OPENMP )
